version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes: 
      - elasticImage:/usr/share/elasticsearch/data
    restart: unless-stopped
      
  minio:
    image: minio/minio:RELEASE.2021-09-09T21-37-07Z
    volumes: 
      - minioImage:/data
    expose: 
      - "9000"
    ports: 
      - 9000:9000
    restart: unless-stopped
    environment: 
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  rabbitmq:
    image: bitnami/rabbitmq:3.9.9
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmqData:/var/lib/rabbitmq
        - rabbitmqLogs:/var/log/rabbitmq
    restart: unless-stopped

volumes:
  minioImage:
    driver: local
  elasticImage:
    driver: local
  rabbitmqData:
    driver: local
  rabbitmqLogs:
    driver: local
